### PR TITLE
Forget Button Endpoint (+ frontend call) & Control for Pre-trained models

### PR DESCRIPTION
**Pull request by leriomaggio**
This PR brings the new `forget` endpoint added to the learning machine backend. 

The endpoint will be accessible via POST request, and it will have the effect to re-instantiate the current Learning Machine model, and to re-calculate probabilities (i.e. predictions) for all the faces in the current board.
For this reason, the endpoint is invoked via POST http method, including reference to all images in board to be passed in to the renewed learning machine model.
Integration in the frontend has been activated too (see `function forget` in `index.html`).

Moreover, _backend_ and _frontend_ also incorporate an extra (query string) parameter to control whether the learning machine model should be used or not as pre-trained. (set to `False` by default).
The same constant value in frontend will be re-used in every method request, for consistency.

Using a non-pretrained model made me realise of #6 

**TODO** 
To be discussed the endpoint to generate and update the Bar chart, and or whether the `forget` EP should also include some extra data currently not returned. 
I think a description of the expected JSON object would be helpful.

### CODE REVIEW

**Comment by leriomaggio** [comment]
@OliverDavis a small step towards fixing Issue in #6
(More details reported in #6 directly). 

In this PR, I've update the `refreshNodeArray` function in `frontend/d8r.js` so that not just links are updated with server response, but also `donut` array of existing nodes.
See **line 132**

**Comment by OliverDavis** [comment]
Actually, the update to the displayed data for the `donut` array already happens (confusingly!) in the `compileData` function, so we should roll back the changes to `refreshNodeArray`. But you're right that the donuts aren't currently updating; I realised I haven't provided an update function to the donut drawing code, so they're not currently changing when the bound data change!

**Comment by leriomaggio** [comment]
ok @OliverDavis thanks for the feedback.
Changes to `d8r.js` reverted. in the PR :)

**Comment by OliverDavis** [comment]
> I think a description of the expected JSON object would be helpful.

Yes, I've just looked at this. I think it should work if the object returned from the `forget` endpoint is the same as the one returned from the `annotate` endpoint (I don't think there's anything else we need back from the server beyond updating the weights for the current faces). But I agree it's not clear what the format should be if we're going to include model fit stats in both.

How about this as a return object for both the `annotate` and `forget` endpoints?

`{
    "data": [current return object],
    "stats": {name, value for model fit stats}
}`

**Comment by OliverDavis** [comment]
This all looks brilliant, @leriomaggio! I've been looking at fixing the donut updates and I think it will take me a while, so let's merge this now and I'll do a separate pull request. I don't think we necessarily need a separate end point for the bar chart; I think we can just update it based on the return from the other endpoints at the same time as we update the nodes. So...

**TODO**
Fix donut updates
Modify return data structure to include model fit stats
Use model fit stats to update bar chart

**Pull request merged**
